# app/api/sync.py
"""
Cross-flavor import / export API.

Direction: flavor variants (e.g. nexus_mec) → main nexus.

  POST /api/v1/profiles/export-code
    Called by flavor-variant users to generate a 6-char one-time code.
    The code expires in 15 minutes.

  POST /api/v1/profiles/import
    Called by main nexus users to consume a flavor export code and pull
    the encrypted profile data into their own account.
"""

import logging
from typing import Any

from fastapi import APIRouter, Body, Depends, HTTPException, Request, status

from app.api.dependencies import (
    get_authenticated_user_payload,
    verify_app_check_token,
)
from app.core.config import settings
from app.core.limiter import limiter
from app.db.users import (
    execute_import,
    fetch_profile,
    fetch_public_user,
    generate_export_code,
)
from app.models import ExportCodeResponse, ImportRequest, ImportResponse

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post(
    "/api/v1/profiles/export-code",
    response_model=ExportCodeResponse,
    summary="Generate a one-time export code (flavor variants only)",
)
@limiter.limit(settings.rate_limit_auth)
def create_export_code(
    request: Request,
    _device: None = Depends(verify_app_check_token),
    auth_user: dict[str, Any] = Depends(get_authenticated_user_payload),  # noqa: B008
) -> ExportCodeResponse:
    """
    Generate a 6-character alphanumeric export code for the authenticated user.

    Only flavor-variant profiles (app_variant != 'nexus') may call this endpoint.
    The code is written to the profile and expires in 15 minutes.
    Any previously active code is silently overwritten.
    """
    _ = request

    user_id = str(auth_user.get("id") or "").strip()
    if not user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authenticated user payload is incomplete.",
        )

    # Verify the caller is a flavor-variant profile (not the main nexus account).
    profile = fetch_profile(user_id)
    if not profile:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Profile not found. Complete onboarding first.",
        )

    user_row = fetch_public_user(user_id)
    app_variant = str(user_row.get("app_variant") or "nexus") if user_row else "nexus"
    if app_variant == "nexus":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                "Export codes can only be generated from a flavor variant account "
                "(e.g. Nexus MEC). The main Nexus account imports data, not exports."
            ),
        )

    code, expires_at = generate_export_code(user_id)
    logger.info(
        "Export code generated",
        extra={"user_id": user_id, "app_variant": app_variant},
    )
    return ExportCodeResponse(code=code, expires_at=expires_at)


@router.post(
    "/api/v1/profiles/import",
    response_model=ImportResponse,
    summary="Import profile data from a flavor variant (main nexus only)",
)
@limiter.limit(settings.rate_limit_auth)
def import_from_flavor(
    request: Request,
    payload: ImportRequest = Body(...),  # noqa: B008
    _device: None = Depends(verify_app_check_token),
    auth_user: dict[str, Any] = Depends(get_authenticated_user_payload),  # noqa: B008
) -> ImportResponse:
    """
    Consume a one-time export code generated by a flavor-variant account.

    Only the main 'nexus' variant may call this endpoint. The import:
      - Copies encrypted PII fields from the source (flavor) profile.
      - Marks the target profile as has_imported_data = True.
      - Invalidates the export code so it cannot be reused.

    Import can only happen once per account.
    """
    _ = request

    user_id = str(auth_user.get("id") or "").strip()
    if not user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authenticated user payload is incomplete.",
        )

    # Verify the caller is the main 'nexus' app variant early
    user_row = fetch_public_user(user_id)
    if not user_row:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User bootstrap row not found. Complete bootstrap first.",
        )
    if user_row.get("app_variant") != "nexus":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Import is only available for the main 'nexus' app variant.",
        )

    copied_fields = execute_import(
        target_user_id=user_id,
        sync_code=payload.sync_code,
        target_variant=str(user_row.get("app_variant") or "nexus"),
    )

    logger.info(
        "Cross-flavor import successful",
        extra={"user_id": user_id, "copied_field_count": len(copied_fields)},
    )
    return ImportResponse(success=True, imported_fields=copied_fields)
