"""Interest taxonomy mappings and sub-interest structures.

Contains the canonical VALID_INTERESTS dictionary mapping top-level interest
categories to their allowed sub-interest sets, used across scoring and validation.
"""

VALID_INTERESTS: dict[str, set[str]] = {
    # --- Tech & Science ---
    "Coding": {
        "Python",
        "Flutter & Dart",
        "Rust",
        "JavaScript & TypeScript",
        "Web Development",
        "AI & Machine Learning",
        "Cybersecurity",
        "Game Development",
        "Cloud & DevOps",
        "Open Source Contribution",
        "Mobile Apps",
        "Embedded Systems",
        "Blockchain & Web3",
    },
    "Science & Discovery": {
        "Astrophysics & Space",
        "Quantum Physics",
        "Neuroscience",
        "Psychology",
        "Marine Biology",
        "Archaeology & History",
        "Genetics & Biotech",
        "Climate Science",
        "Chemistry",
        "Mathematics",
        "Citizen Science",
    },
    "Gadgets & Hardware": {
        "PC Building",
        "Virtual Reality (VR)",
        "Augmented Reality (AR)",
        "Drones & Quadcopters",
        "IoT & Smart Home",
        "Mechanical Keyboards",
        "3D Printing",
        "Robotics",
        "Amateur Radio (Ham)",
    },
    "Math & Logic": {
        "Cryptography",
        "Data Analysis",
        "Game Theory",
        "Mathematical Puzzles",
        "Algorithms",
        "Chess & Strategy Games",
    },
    # --- Entertainment & Media ---
    "TV & Series": {
        "Horror Shows",
        "Sci-Fi & Fantasy",
        "Documentaries",
        "True Crime",
        "Sitcoms & Comedy",
        "K-Dramas",
        "Anime & Manga",
        "Reality TV",
        "Historical Drama",
        "Talk Shows",
        "Mini-Series & Limited",
        "Soap Operas",
        "Telenovelas",
    },
    "Movies & Cinema": {
        "Indie & Art House",
        "Hollywood Blockbusters",
        "Classic Films",
        "Psychological Thrillers",
        "Animation & Pixar",
        "Foreign Language Films",
        "Action & Adventure",
        "Horror",
        "Rom-Coms",
        "Bollywood",
        "Martial Arts Films",
        "Documentaries",
    },
    "Gaming": {
        "RPGs (Role-Playing)",
        "FPS (First-Person)",
        "RTS (Strategy)",
        "MMORPGs",
        "Cozy & Casual Games",
        "Competitive Esports",
        "Retro & Arcade",
        "Tabletop & D&D",
        "Modern Board Games",
        "Card Games (TCG)",
        "Puzzle Games",
        "Horror Games",
        "Simulation & Sandbox",
        "Sports Games",
        "Fighting Games",
        "Mobile Gaming",
    },
    "Music": {
        "Rock & Alternative",
        "Metal & Heavy",
        "Pop",
        "R&B & Soul",
        "Hip Hop & Rap",
        "Indie & Folk",
        "Classical & Opera",
        "Jazz & Blues",
        "EDM & House",
        "Techno & Industrial",
        "Synthwave & Retrowave",
        "Lo-Fi & Chillbeats",
        "Reggae & Dancehall",
        "Afrobeats & Afropop",
        "Latin & Reggaeton",
        "K-Pop",
        "Country & Bluegrass",
        "Gospel & Worship",
        "Punk & Hardcore",
        "Ambient & Drone",
        "Vinyl Records",
        "Live Concerts & Festivals",
        "Music Production",
    },
    "Comedy & Memes": {
        "Meme Culture",
        "Stand-Up Comedy",
        "Sketch Comedy",
        "Improv",
        "Internet Humour",
        "Satire",
        "Podcasts (Comedy)",
    },
    "Podcasts & Audio": {
        "True Crime Podcasts",
        "News & Current Affairs",
        "Self-Improvement Podcasts",
        "Science Podcasts",
        "Storytelling & Fiction",
        "Interview Shows",
        "Audiobooks",
    },
    # --- Sports & Outdoors ---
    "Fitness & Training": {
        "Weightlifting",
        "Powerlifting",
        "CrossFit",
        "Calisthenics",
        "Yoga",
        "Pilates",
        "HIIT & Cardio",
        "Cycling & Spinning",
        "Gymnastics",
        "Running & Marathons",
        "Triathlons",
        "Personal Training",
        "Dance Fitness",
    },
    "Martial Arts & Combat": {
        "Boxing",
        "Muay Thai",
        "Brazilian Jiu-Jitsu (BJJ)",
        "Wrestling",
        "MMA",
        "Karate",
        "Judo",
        "Taekwondo",
        "Kickboxing",
        "Krav Maga",
        "Capoeira",
        "Kung Fu",
    },
    "Team Sports": {
        "Football (Soccer)",
        "Basketball",
        "Volleyball",
        "Baseball",
        "Cricket",
        "American Football",
        "Rugby",
        "Ice Hockey",
        "Lacrosse",
        "Water Polo",
        "Handball",
        "Ultimate Frisbee",
        "Netball",
    },
    "Individual Sports": {
        "Tennis",
        "Badminton",
        "Table Tennis",
        "Golf",
        "Archery",
        "Fencing",
        "Billiards & Pool",
        "Track & Field",
        "Cycling (Road)",
        "Cycling (MTB)",
        "Skateboarding",
        "Parkour",
        "Equestrian",
    },
    "Water & Winter Sports": {
        "Swimming",
        "Open Water Swimming",
        "Surfing & Bodyboarding",
        "Kayaking & Paddle",
        "Scuba Diving",
        "Snorkelling",
        "Sailing",
        "Kitesurfing",
        "Skiing",
        "Snowboarding",
        "Ice Skating",
        "Freediving",
    },
    "Outdoor Adventure": {
        "Hiking & Trekking",
        "Rock Climbing",
        "Bouldering",
        "Camping & Bushcraft",
        "Backpacking",
        "Mountaineering",
        "Trail Running",
        "Geocaching",
        "Foraging",
        "Caving & Spelunking",
        "Paragliding",
        "Skydiving",
        "Hunting & Fishing",
    },
    "Watching Sports": {
        "Football Watching",
        "Basketball Watching",
        "Formula 1",
        "MMA & UFC",
        "Cricket Watching",
        "Tennis Watching",
        "Olympic Sports",
        "Fantasy Leagues",
    },
    # --- Creative & Arts ---
    "Visual Arts": {
        "Watercolor Painting",
        "Oil & Acrylics",
        "Sketching & Charcoal",
        "Digital Illustration",
        "Calligraphy",
        "Pottery & Ceramics",
        "Origami & Papercraft",
        "Printmaking",
        "Sculpture",
        "Street Art & Graffiti",
        "Collage & Mixed Media",
    },
    "Design & Styling": {
        "UI/UX Design",
        "Graphic Design",
        "Fashion Design",
        "Interior Design",
        "3D Modeling",
        "Architecture",
        "Typesetting",
        "Logo Design",
        "Jewellery Making",
    },
    "Photography & Video": {
        "Landscape & Nature",
        "Portrait & Studio",
        "Street & Documentary",
        "Film & Analog",
        "Drone Videography",
        "Video Editing",
        "YouTube & Content Creation",
        "Wedding & Events",
    },
    "Performing Arts": {
        "Ballet",
        "Contemporary Dance",
        "Hip Hop Dance",
        "Ballroom & Latin Dance",
        "Salsa & Bachata",
        "Traditional Dance",
        "Acting & Theater",
        "Musical Theater",
        "Musical Instruments",
        "Singing & Vocals",
        "Choir",
        "Stand-Up & Improv",
        "Circus Arts",
        "Magic & Illusion",
    },
    "Writing & Literature": {
        "Creative Fiction",
        "Fantasy & Sci-Fi Writing",
        "Poetry & Prose",
        "Blogging & Journalism",
        "Journaling",
        "Screenwriting",
        "Game Writing",
        "Technical Writing",
    },
    "Crafts & DIY": {
        "Knitting & Crocheting",
        "Sewing & Embroidery",
        "Woodworking & Carpentry",
        "Leatherworking",
        "Candle & Soap Making",
        "Model Building",
        "RC Vehicles",
        "Lego & Sets",
        "Macramé",
        "Resin Art",
        "Home Renovation & DIY",
    },
    # --- Books & Reading ---
    "Fiction": {
        "Fantasy",
        "Science Fiction",
        "Literary Fiction",
        "Historical Fiction",
        "Romance",
        "Thriller & Mystery",
        "Horror",
        "Magical Realism",
        "Graphic Novels & Comics",
        "Manga",
    },
    "Non-Fiction": {
        "Biographies & Memoirs",
        "Self-Help",
        "Philosophy",
        "History",
        "Science & Nature",
        "Psychology",
        "Business & Economics",
        "True Crime Books",
        "Political Theory",
        "Travel Writing",
        "Essays & Criticism",
        "Spirituality & Religion",
    },
    "Reading Habits": {
        "Book Clubs",
        "Audiobooks",
        "eBooks",
        "Second-Hand Books",
        "Reading Challenges",
        "Rare & Antique Books",
    },
    # --- Food & Drink ---
    "Cooking & Culinary": {
        "Baking & Pastry",
        "Sourdough Bread",
        "BBQ & Grilling",
        "Vegan & Vegetarian Cooking",
        "World Cuisines",
        "Fine Dining",
        "Fermentation & Pickling",
        "Meal Prep & Nutrition",
        "Street Food",
        "Sushi & Japanese Cuisine",
        "Middle Eastern Cuisine",
        "Italian Cooking",
        "Indian Cooking",
    },
    "Beverages": {
        "Specialty Coffee",
        "Matcha & Green Tea",
        "Loose Leaf Tea",
        "Wine Tasting",
        "Craft Beer & Brewing",
        "Mixology & Cocktails",
        "Natural Wine",
        "Kombucha & Fermented Drinks",
        "Whisky & Spirits",
        "Non-Alcoholic Cocktails",
    },
    "Food Culture": {
        "Restaurant Hopping",
        "Food Photography",
        "Food Blogging",
        "Farmers Markets",
        "Food Festivals",
    },
    # --- Travel & Adventure ---
    "Travel Style": {
        "Backpacking",
        "Solo Travel",
        "Luxury Travel",
        "Budget Travel",
        "Van Life & Overlanding",
        "Road Trips",
        "Cruise Travel",
        "Family Travel",
        "Workcation & Remote Work",
        "Digital Nomad Lifestyle",
    },
    "Destinations": {
        "Europe",
        "Southeast Asia",
        "East Asia",
        "South Asia",
        "Africa",
        "Latin America",
        "Middle East",
        "North America",
        "Oceania & Pacific",
        "Arctic & Antarctic",
    },
    "Travel Interests": {
        "Cultural Immersion",
        "Historical Sites & Ruins",
        "Food Tourism",
        "Wildlife Safaris",
        "National Parks",
        "Beach & Island Hopping",
        "City Breaks",
        "Festival Travel",
        "Language Immersion",
        "Voluntourism",
    },
    # --- Lifestyle & Wellness ---
    "Mind & Wellbeing": {
        "Meditation",
        "Mindfulness",
        "Breathwork",
        "Cold Plunge & Ice Baths",
        "Philosophy",
        "Self-Improvement",
        "Therapy & Inner Work",
        "Sleep Optimisation",
        "Digital Detox",
    },
    "Nature & Gardening": {
        "Houseplants",
        "Bonsai",
        "Vegetable Gardening",
        "Aquascaping",
        "Foraging & Herbalism",
        "Beekeeping",
        "Permaculture",
    },
    "Fashion & Style": {
        "Vintage & Thrifting",
        "Sneaker Culture",
        "Streetwear",
        "Luxury & Designer",
        "Sustainable Fashion",
        "Cottagecore",
        "Gothic & Alternative",
        "Haul Culture",
        "Cosplay",
    },
    "Collecting & Hobbies": {
        "Watch Collecting",
        "Book Collecting",
        "Vinyl Records",
        "Trading Cards",
        "Coins & Currency",
        "Stamps",
        "Art Collecting",
        "Antiques & Vintage",
        "Figurines & Statues",
        "Sports Memorabilia",
    },
    "Pets & Animals": {
        "Dog Training",
        "Cat Care",
        "Exotic Pets",
        "Bird Watching",
        "Aquariums",
        "Animal Rescue & Fostering",
        "Wildlife Photography",
    },
    # --- Finance & Business ---
    "Investing": {
        "Stock Market",
        "Index Funds & ETFs",
        "Cryptocurrency",
        "NFTs & Web3",
        "Real Estate Investing",
        "Angel Investing",
        "Options & Derivatives",
        "Commodities",
    },
    "Business & Entrepreneurship": {
        "Startups",
        "Freelancing",
        "E-commerce",
        "Content Creation & Monetisation",
        "Side Hustles",
        "Venture Capital",
        "Marketing & Growth",
        "Product Management",
    },
    "Personal Finance": {
        "FIRE Movement",
        "Frugal Living",
        "Budgeting",
        "Passive Income",
        "Financial Independence",
    },
    # --- Social & Activism ---
    "Community & Volunteering": {
        "Volunteering",
        "Community Organising",
        "Mutual Aid",
        "Mentorship",
        "Charity & Fundraising",
        "Non-Profit Work",
    },
    "Activism & Advocacy": {
        "Environmental Activism",
        "LGBTQ+ Advocacy",
        "Racial Justice",
        "Gender Equality",
        "Disability Rights",
        "Animal Rights",
        "Anti-War & Peace",
        "Digital Rights",
    },
    "Politics & Society": {
        "Political Science",
        "Current Events",
        "Debate & Discourse",
        "Geopolitics",
        "Local Politics",
        "Journalism & Media Literacy",
    },
    "Language & Culture": {
        "Language Learning",
        "Linguistics",
        "Cultural Exchange",
        "Pen Pals & Letter Writing",
        "Anthropology",
    },
    # --- Spirituality & Esoteric ---
    "Spiritual Practices": {
        "Meditation & Prayer",
        "Yoga Philosophy",
        "Buddhism",
        "Hinduism & Vedanta",
        "Sufism",
        "Kabbalah",
        "Shamanism",
        "Druidry & Paganism",
    },
    "Mystical & Esoteric": {
        "Astrology",
        "Tarot & Oracle",
        "Numerology",
        "Crystal Healing",
        "Manifestation",
        "Human Design",
        "Reiki & Energy Healing",
        "Witchcraft",
    },
    "Paranormal & Unexplained": {
        "Ghosts & Hauntings",
        "UFOs & Extraterrestrial",
        "Conspiracy Theories",
        "Cryptids",
        "Near-Death Experiences",
    },
    # --- Cars & Motors ---
    "Cars": {
        "Car Culture & Shows",
        "Classic & Vintage Cars",
        "JDM (Japanese Domestic Market)",
        "American Muscle",
        "European Sports Cars",
        "Electric Vehicles",
        "Car Modification & Tuning",
        "Off-Road & 4x4",
        "Autocross & Track Days",
        "Formula 1",
        "Rally & Motorsport",
    },
    "Motorcycles & Bikes": {
        "Motorcycles & Touring",
        "Superbikes",
        "Custom & Chopper Builds",
        "Dirt Bikes & Motocross",
        "Cycling (Road)",
        "Mountain Biking",
        "BMX",
        "E-Bikes",
    },
    "Aviation & Marine": {
        "Aviation & Flying",
        "Sailing",
        "Boating & Yachting",
        "Model Aircraft",
    },
}
