"""Profile identity and lifestyle option sets.

Contains canonical choice sets for gender identities, sexualities, pronouns,
spoken languages, drinking, smoking, children plans, and religious beliefs.
"""

GENDER_CHOICES = {
    # Binary / cisgender
    "Man",
    "Woman",
    "Cisgender Man",
    "Cisgender Woman",
    # Transgender
    "Transgender Man",
    "Transgender Woman",
    "Transgender",
    # Non-binary umbrella
    "Non-binary",
    "Genderqueer",
    "Genderfluid",
    "Agender",
    "Gender Non-Conforming",
    "Androgynous",
    "Neutrois",
    "Maverique",
    # Multi / split gender
    "Bigender",
    "Trigender",
    "Multigender",
    "Pangender",
    # Demi variants
    "Demiboy",
    "Demigirl",
    "Demi-non-binary",
    # Cultural / other
    "Two-Spirit",
    "Third Gender",
    "Intersex",
    "Xenogender",
    # Open / fluid
    "Queer",
    "Questioning",
    "Prefer not to say",
}

SEXUALITY_CHOICES = {
    # Common orientations
    "Straight / Heterosexual",
    "Gay",
    "Lesbian",
    "Bisexual",
    "Pansexual",
    "Omnisexual",
    "Polysexual",
    # Asexual spectrum
    "Asexual",
    "Graysexual",
    "Demisexual",
    "Cupiosexual",
    "Lithosexual",
    # Aromantic spectrum
    "Aromantic",
    "Aroace",
    "Greyromantic",
    "Demiromantic",
    # Community shorthand
    "Sapphic",
    "Achillean",
    "Queer",
    # Fluid / open
    "Fluid",
    "Skoliosexual",
    "Questioning",
    "Prefer not to say",
}

PRONOUNS_CHOICES = {
    # Common
    "he/him",
    "she/her",
    "they/them",
    # Mixed
    "he/they",
    "she/they",
    "he/she",
    "he/she/they",
    # Neopronouns
    "xe/xem",
    "ze/zir",
    "ze/hir",
    "ey/em",
    "fae/faer",
    "per/per",
    "e/em",
    "ve/ver",
    # Other
    "it/its",
    "any/all",
    "Use my name",
    "Prefer not to say",
}

LANGUAGES_CHOICES = {
    # Most spoken worldwide
    "English",
    "Mandarin Chinese",
    "Hindi",
    "Spanish",
    "French",
    "Arabic",
    "Bengali",
    "Portuguese",
    "Russian",
    "Urdu",
    "Indonesian / Malay",
    "German",
    "Japanese",
    "Telugu",
    "Marathi",
    "Tamil",
    "Cantonese",
    "Korean",
    "Vietnamese",
    "Turkish",
    "Italian",
    "Punjabi",
    "Gujarati",
    "Persian / Farsi",
    "Polish",
    "Ukrainian",
    "Kannada",
    "Malayalam",
    "Burmese",
    "Thai",
    "Sinhala",
    "Nepali",
    "Tagalog / Filipino",
    "Javanese",
    "Sundanese",
    "Wu Chinese",
    "Swahili",
    "Hausa",
    "Yoruba",
    "Igbo",
    "Amharic",
    "Oromo",
    "Tigrinya",
    "Somali",
    "Zulu",
    "Xhosa",
    "Shona",
    "Kinyarwanda",
    "Lingala",
    "Fula",
    "Wolof",
    "Twi / Akan",
    "Nyanja / Chewa",
    "Sotho",
    "Tswana",
    "Afrikaans",
    # South / Southeast Asia
    "Pashto",
    "Dari",
    "Sindhi",
    "Maithili",
    "Assamese",
    "Khmer",
    "Lao",
    # Central Asia & Caucasus
    "Uzbek",
    "Kazakh",
    "Kyrgyz",
    "Turkmen",
    "Tajik",
    "Azerbaijani",
    "Georgian",
    "Armenian",
    "Kurdish",
    "Mongolian",
    "Tibetan",
    "Uyghur",
    # European
    "Dutch",
    "Greek",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "Hungarian",
    "Romanian",
    "Czech",
    "Slovak",
    "Bulgarian",
    "Serbian",
    "Croatian",
    "Bosnian",
    "Slovenian",
    "Macedonian",
    "Albanian",
    "Lithuanian",
    "Latvian",
    "Estonian",
    "Belarusian",
    "Catalan",
    "Galician",
    "Basque",
    "Welsh",
    "Irish",
    "Scottish Gaelic",
    "Icelandic",
    "Maltese",
    "Luxembourgish",
    # Middle East & North Africa
    "Hebrew",
    # Pacific
    "Malagasy",
    "Fijian",
    "Māori",
    "Hawaiian",
    "Samoan",
    "Tongan",
    # Sign languages
    "American Sign Language (ASL)",
    "British Sign Language (BSL)",
    "International Sign",
    # Constructed / classical
    "Esperanto",
    "Latin",
    "Other",
}

CAUSES_SUPPORTED_CHOICES = {
    # Environment & Planet
    "Climate Action",
    "Renewable Energy",
    "Biodiversity & Wildlife",
    "Ocean Conservation",
    "Deforestation & Reforestation",
    "Clean Air",
    "Clean Water & Sanitation",
    "Zero Waste & Recycling",
    "Sustainable Agriculture",
    "Animal Protection",
    "Veganism & Animal Rights",
    # People & Society
    "Human Rights",
    "Gender Equality",
    "LGBTQ+ Rights",
    "Racial Justice",
    "Indigenous Rights",
    "Disability Rights",
    "Children's Rights",
    "Elder Care",
    "Refugee & Migrant Rights",
    "Anti-Trafficking",
    "Prison Reform",
    "Voting Rights & Democracy",
    # Health & Wellbeing
    "Mental Health Advocacy",
    "Global Health",
    "Reproductive Rights",
    "Substance Abuse & Recovery",
    "Nutrition & Food Security",
    "Rare Disease Research",
    # Education & Economy
    "Education Access",
    "Digital Literacy",
    "Economic Development",
    "Poverty Alleviation",
    "Fair Trade",
    "Entrepreneurship & Small Business",
    "Financial Inclusion",
    # Science & Technology
    "Scientific Research",
    "Tech Ethics",
    "AI Safety",
    "Open Source & Open Knowledge",
    "Space Exploration",
    # Culture & Community
    "Arts & Culture Preservation",
    "Community Development",
    "Volunteerism",
    "Religious Freedom",
    "Free Speech & Press Freedom",
    # Humanitarian
    "Disaster Relief",
    "Hunger & Food Banks",
    "Homelessness",
    "Peace & Conflict Resolution",
    "Nuclear Disarmament",
}

PETS_CHOICES = {
    # Common companions
    "Dog",
    "Cat",
    "Rabbit",
    "Ferret",
    # Small mammals
    "Hamster",
    "Guinea Pig",
    "Gerbil",
    "Mouse",
    "Rat",
    "Chinchilla",
    "Hedgehog",
    "Sugar Glider",
    "Degu",
    "Prairie Dog",
    # Birds
    "Parrot",
    "Budgie / Parakeet",
    "Cockatiel",
    "Cockatoo",
    "Lovebird",
    "Finch / Canary",
    "Macaw",
    "Pigeon / Dove",
    "Chicken / Poultry",
    # Reptiles
    "Gecko",
    "Bearded Dragon",
    "Tortoise / Turtle",
    "Snake",
    "Iguana",
    "Chameleon",
    "Monitor Lizard",
    # Amphibians
    "Frog / Toad",
    "Axolotl",
    "Salamander",
    # Aquatic
    "Fish (Freshwater)",
    "Fish (Marine / Reef)",
    "Shrimp / Crayfish",
    "Crab",
    # Invertebrates
    "Tarantula",
    "Scorpion",
    "Stick Insect",
    "Snail",
    # Larger / farm-type
    "Horse / Pony",
    "Goat",
    "Sheep",
    "Pig (Micro)",
    "Alpaca / Llama",
    # None
    "No Pets",
}

DRINKING_CHOICES = {"Never", "Occasionally", "Socially", "Regularly"}

SMOKING_CHOICES = {"Never", "Occasionally", "Socially", "Regularly"}

CHILDREN_PLANS_CHOICES = {
    "Want kids",
    "Don't want kids",
    "Undecided",
    "Not specified",
}

RELIGIOUS_BELIEFS_CHOICES = {
    # Non-religious / philosophical
    "Atheist",
    "Agnostic",
    "Secular Humanist",
    "Deist",
    "Pantheist",
    # Spiritual but non-denominational
    "Spiritual but not religious",
    "New Age",
    "Pagan / Wiccan",
    # Abrahamic
    "Christian",
    "Catholic",
    "Protestant",
    "Orthodox Christian",
    "Muslim (Sunni)",
    "Muslim (Shia)",
    "Jewish",
    "Jewish (Orthodox)",
    # Dharmic
    "Hindu",
    "Buddhist",
    "Sikh",
    "Jain",
    # East Asian
    "Taoist",
    "Shinto",
    "Confucianist",
    # Other organised religions
    "Bahá'í",
    "Zoroastrian",
    "Rastafari",
    "Druze",
    "Yazidi",
    "Unitarian Universalist",
    # Indigenous / folk
    "Indigenous / Traditional",
    "Animist",
    # Catch-all
    "Other",
    "Prefer not to say",
}
