"""Database chat conversation, messaging, and E2EE key persistence package."""

from app.db.chat.chat import (
    close_conversation_for_match_action,
    create_event_with_message,
    decrypt_event_row,
    delete_conversation_chat_media,
    fetch_conversation_for_match,
    fetch_conversation_participants,
    fetch_conversations_for_user,
    fetch_due_event_reminders,
    fetch_due_safety_reminders,
    fetch_event,
    fetch_presence,
    fetch_started_match_ids,
    fetch_user_share_flags,
    get_or_create_conversation,
    insert_message,
    mark_messages_read,
    mark_reminder_sent,
    mark_safety_reminder_sent,
    reopen_conversations_for_reactivation,
    update_event_status,
    upsert_presence_heartbeat,
)
from app.db.chat.keys import (
    bulk_insert_one_time_prekeys,
    count_unused_one_time_prekeys,
    fetch_identity_key,
    fetch_key_bundle,
    has_active_match,
    mark_session_established,
    upsert_identity_key,
    upsert_signed_prekey,
)

__all__ = [
    # keys
    "bulk_insert_one_time_prekeys",
    # chat
    "close_conversation_for_match_action",
    "count_unused_one_time_prekeys",
    "create_event_with_message",
    "decrypt_event_row",
    "delete_conversation_chat_media",
    "fetch_conversation_for_match",
    "fetch_conversation_participants",
    "fetch_conversations_for_user",
    "fetch_due_event_reminders",
    "fetch_due_safety_reminders",
    "fetch_event",
    "fetch_identity_key",
    "fetch_key_bundle",
    "fetch_presence",
    "fetch_started_match_ids",
    "fetch_user_share_flags",
    "get_or_create_conversation",
    "has_active_match",
    "insert_message",
    "mark_messages_read",
    "mark_reminder_sent",
    "mark_safety_reminder_sent",
    "mark_session_established",
    "reopen_conversations_for_reactivation",
    "update_event_status",
    "upsert_identity_key",
    "upsert_presence_heartbeat",
    "upsert_signed_prekey",
]
