import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class ParentInterest {
  const ParentInterest({required this.name, required this.subInterests});
  final String name;
  final List<String> subInterests;
}

class InterestCategory {
  const InterestCategory({
    required this.name,
    required this.icon,
    required this.parents,
  });
  final String name;
  final IconData icon;
  final List<ParentInterest> parents;
}

const List<InterestCategory> interestsCategories = [
  InterestCategory(
    name: 'Tech & Science',
    icon: LucideIcons.cpu,
    parents: [
      ParentInterest(
        name: 'Coding',
        subInterests: [
          'Python',
          'Flutter & Dart',
          'Rust',
          'JavaScript & TypeScript',
          'Web Development',
          'AI & Machine Learning',
          'Cybersecurity',
          'Game Development',
          'Cloud & DevOps',
          'Open Source Contribution',
          'Mobile Apps',
          'Embedded Systems',
          'Blockchain & Web3',
        ],
      ),
      ParentInterest(
        name: 'Science & Discovery',
        subInterests: [
          'Astrophysics & Space',
          'Quantum Physics',
          'Neuroscience',
          'Psychology',
          'Marine Biology',
          'Archaeology & History',
          'Genetics & Biotech',
          'Climate Science',
          'Chemistry',
          'Mathematics',
          'Citizen Science',
        ],
      ),
      ParentInterest(
        name: 'Gadgets & Hardware',
        subInterests: [
          'PC Building',
          'Virtual Reality (VR)',
          'Augmented Reality (AR)',
          'Drones & Quadcopters',
          'IoT & Smart Home',
          'Mechanical Keyboards',
          '3D Printing',
          'Robotics',
          'Amateur Radio (Ham)',
        ],
      ),
      ParentInterest(
        name: 'Math & Logic',
        subInterests: [
          'Cryptography',
          'Data Analysis',
          'Game Theory',
          'Mathematical Puzzles',
          'Algorithms',
          'Chess & Strategy Games',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Entertainment & Media',
    icon: LucideIcons.film,
    parents: [
      ParentInterest(
        name: 'TV & Series',
        subInterests: [
          'Horror Shows',
          'Sci-Fi & Fantasy',
          'Documentaries',
          'True Crime',
          'Sitcoms & Comedy',
          'K-Dramas',
          'Anime & Manga',
          'Reality TV',
          'Historical Drama',
          'Talk Shows',
          'Mini-Series & Limited',
          'Soap Operas',
          'Telenovelas',
        ],
      ),
      ParentInterest(
        name: 'Movies & Cinema',
        subInterests: [
          'Indie & Art House',
          'Hollywood Blockbusters',
          'Classic Films',
          'Psychological Thrillers',
          'Animation & Pixar',
          'Foreign Language Films',
          'Action & Adventure',
          'Horror',
          'Rom-Coms',
          'Bollywood',
          'Martial Arts Films',
          'Documentaries',
        ],
      ),
      ParentInterest(
        name: 'Gaming',
        subInterests: [
          'RPGs (Role-Playing)',
          'FPS (First-Person)',
          'RTS (Strategy)',
          'MMORPGs',
          'Cozy & Casual Games',
          'Competitive Esports',
          'Retro & Arcade',
          'Tabletop & D&D',
          'Modern Board Games',
          'Card Games (TCG)',
          'Puzzle Games',
          'Horror Games',
          'Simulation & Sandbox',
          'Sports Games',
          'Fighting Games',
          'Mobile Gaming',
        ],
      ),
      ParentInterest(
        name: 'Music',
        subInterests: [
          'Rock & Alternative',
          'Metal & Heavy',
          'Pop',
          'R&B & Soul',
          'Hip Hop & Rap',
          'Indie & Folk',
          'Classical & Opera',
          'Jazz & Blues',
          'EDM & House',
          'Techno & Industrial',
          'Synthwave & Retrowave',
          'Lo-Fi & Chillbeats',
          'Reggae & Dancehall',
          'Afrobeats & Afropop',
          'Latin & Reggaeton',
          'K-Pop',
          'Country & Bluegrass',
          'Gospel & Worship',
          'Punk & Hardcore',
          'Ambient & Drone',
          'Vinyl Records',
          'Live Concerts & Festivals',
          'Music Production',
        ],
      ),
      ParentInterest(
        name: 'Comedy & Memes',
        subInterests: [
          'Meme Culture',
          'Stand-Up Comedy',
          'Sketch Comedy',
          'Improv',
          'Internet Humour',
          'Satire',
          'Podcasts (Comedy)',
        ],
      ),
      ParentInterest(
        name: 'Podcasts & Audio',
        subInterests: [
          'True Crime Podcasts',
          'News & Current Affairs',
          'Self-Improvement Podcasts',
          'Science Podcasts',
          'Storytelling & Fiction',
          'Interview Shows',
          'Audiobooks',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Sports & Outdoors',
    icon: LucideIcons.trophy,
    parents: [
      ParentInterest(
        name: 'Fitness & Training',
        subInterests: [
          'Weightlifting',
          'Powerlifting',
          'CrossFit',
          'Calisthenics',
          'Yoga',
          'Pilates',
          'HIIT & Cardio',
          'Cycling & Spinning',
          'Gymnastics',
          'Running & Marathons',
          'Triathlons',
          'Personal Training',
          'Dance Fitness',
        ],
      ),
      ParentInterest(
        name: 'Martial Arts & Combat',
        subInterests: [
          'Boxing',
          'Muay Thai',
          'Brazilian Jiu-Jitsu (BJJ)',
          'Wrestling',
          'MMA',
          'Karate',
          'Judo',
          'Taekwondo',
          'Kickboxing',
          'Krav Maga',
          'Capoeira',
          'Kung Fu',
        ],
      ),
      ParentInterest(
        name: 'Team Sports',
        subInterests: [
          'Football (Soccer)',
          'Basketball',
          'Volleyball',
          'Baseball',
          'Cricket',
          'American Football',
          'Rugby',
          'Ice Hockey',
          'Lacrosse',
          'Water Polo',
          'Handball',
          'Ultimate Frisbee',
          'Netball',
        ],
      ),
      ParentInterest(
        name: 'Individual Sports',
        subInterests: [
          'Tennis',
          'Badminton',
          'Table Tennis',
          'Golf',
          'Archery',
          'Fencing',
          'Billiards & Pool',
          'Track & Field',
          'Cycling (Road)',
          'Cycling (MTB)',
          'Skateboarding',
          'Parkour',
          'Equestrian',
        ],
      ),
      ParentInterest(
        name: 'Water & Winter Sports',
        subInterests: [
          'Swimming',
          'Open Water Swimming',
          'Surfing & Bodyboarding',
          'Kayaking & Paddle',
          'Scuba Diving',
          'Snorkelling',
          'Sailing',
          'Kitesurfing',
          'Skiing',
          'Snowboarding',
          'Ice Skating',
          'Freediving',
        ],
      ),
      ParentInterest(
        name: 'Outdoor Adventure',
        subInterests: [
          'Hiking & Trekking',
          'Rock Climbing',
          'Bouldering',
          'Camping & Bushcraft',
          'Backpacking',
          'Mountaineering',
          'Trail Running',
          'Geocaching',
          'Foraging',
          'Caving & Spelunking',
          'Paragliding',
          'Skydiving',
          'Hunting & Fishing',
        ],
      ),
      ParentInterest(
        name: 'Watching Sports',
        subInterests: [
          'Football Watching',
          'Basketball Watching',
          'Formula 1',
          'MMA & UFC',
          'Cricket Watching',
          'Tennis Watching',
          'Olympic Sports',
          'Fantasy Leagues',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Creative & Arts',
    icon: LucideIcons.palette,
    parents: [
      ParentInterest(
        name: 'Visual Arts',
        subInterests: [
          'Watercolor Painting',
          'Oil & Acrylics',
          'Sketching & Charcoal',
          'Digital Illustration',
          'Calligraphy',
          'Pottery & Ceramics',
          'Origami & Papercraft',
          'Printmaking',
          'Sculpture',
          'Street Art & Graffiti',
          'Collage & Mixed Media',
        ],
      ),
      ParentInterest(
        name: 'Design & Styling',
        subInterests: [
          'UI/UX Design',
          'Graphic Design',
          'Fashion Design',
          'Interior Design',
          '3D Modeling',
          'Architecture',
          'Typesetting',
          'Logo Design',
          'Jewellery Making',
        ],
      ),
      ParentInterest(
        name: 'Photography & Video',
        subInterests: [
          'Landscape & Nature',
          'Portrait & Studio',
          'Street & Documentary',
          'Film & Analog',
          'Drone Videography',
          'Video Editing',
          'YouTube & Content Creation',
          'Wedding & Events',
        ],
      ),
      ParentInterest(
        name: 'Performing Arts',
        subInterests: [
          'Ballet',
          'Contemporary Dance',
          'Hip Hop Dance',
          'Ballroom & Latin Dance',
          'Salsa & Bachata',
          'Traditional Dance',
          'Acting & Theater',
          'Musical Theater',
          'Musical Instruments',
          'Singing & Vocals',
          'Choir',
          'Stand-Up & Improv',
          'Circus Arts',
          'Magic & Illusion',
        ],
      ),
      ParentInterest(
        name: 'Writing & Literature',
        subInterests: [
          'Creative Fiction',
          'Fantasy & Sci-Fi Writing',
          'Poetry & Prose',
          'Blogging & Journalism',
          'Journaling',
          'Screenwriting',
          'Game Writing',
          'Technical Writing',
        ],
      ),
      ParentInterest(
        name: 'Crafts & DIY',
        subInterests: [
          'Knitting & Crocheting',
          'Sewing & Embroidery',
          'Woodworking & Carpentry',
          'Leatherworking',
          'Candle & Soap Making',
          'Model Building',
          'RC Vehicles',
          'Lego & Sets',
          'Macramé',
          'Resin Art',
          'Home Renovation & DIY',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Books & Reading',
    icon: LucideIcons.bookOpen,
    parents: [
      ParentInterest(
        name: 'Fiction',
        subInterests: [
          'Fantasy',
          'Science Fiction',
          'Literary Fiction',
          'Historical Fiction',
          'Romance',
          'Thriller & Mystery',
          'Horror',
          'Magical Realism',
          'Graphic Novels & Comics',
          'Manga',
        ],
      ),
      ParentInterest(
        name: 'Non-Fiction',
        subInterests: [
          'Biographies & Memoirs',
          'Self-Help',
          'Philosophy',
          'History',
          'Science & Nature',
          'Psychology',
          'Business & Economics',
          'True Crime Books',
          'Political Theory',
          'Travel Writing',
          'Essays & Criticism',
          'Spirituality & Religion',
        ],
      ),
      ParentInterest(
        name: 'Reading Habits',
        subInterests: [
          'Book Clubs',
          'Audiobooks',
          'eBooks',
          'Second-Hand Books',
          'Reading Challenges',
          'Rare & Antique Books',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Food & Drink',
    icon: LucideIcons.coffee,
    parents: [
      ParentInterest(
        name: 'Cooking & Culinary',
        subInterests: [
          'Baking & Pastry',
          'Sourdough Bread',
          'BBQ & Grilling',
          'Vegan & Vegetarian Cooking',
          'World Cuisines',
          'Fine Dining',
          'Fermentation & Pickling',
          'Meal Prep & Nutrition',
          'Street Food',
          'Sushi & Japanese Cuisine',
          'Middle Eastern Cuisine',
          'Italian Cooking',
          'Indian Cooking',
        ],
      ),
      ParentInterest(
        name: 'Beverages',
        subInterests: [
          'Specialty Coffee',
          'Matcha & Green Tea',
          'Loose Leaf Tea',
          'Wine Tasting',
          'Craft Beer & Brewing',
          'Mixology & Cocktails',
          'Natural Wine',
          'Kombucha & Fermented Drinks',
          'Whisky & Spirits',
          'Non-Alcoholic Cocktails',
        ],
      ),
      ParentInterest(
        name: 'Food Culture',
        subInterests: [
          'Restaurant Hopping',
          'Food Photography',
          'Food Blogging',
          'Farmers Markets',
          'Food Festivals',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Travel & Adventure',
    icon: LucideIcons.globe,
    parents: [
      ParentInterest(
        name: 'Travel Style',
        subInterests: [
          'Backpacking',
          'Solo Travel',
          'Luxury Travel',
          'Budget Travel',
          'Van Life & Overlanding',
          'Road Trips',
          'Cruise Travel',
          'Family Travel',
          'Workcation & Remote Work',
          'Digital Nomad Lifestyle',
        ],
      ),
      ParentInterest(
        name: 'Destinations',
        subInterests: [
          'Europe',
          'Southeast Asia',
          'East Asia',
          'South Asia',
          'Africa',
          'Latin America',
          'Middle East',
          'North America',
          'Oceania & Pacific',
          'Arctic & Antarctic',
        ],
      ),
      ParentInterest(
        name: 'Travel Interests',
        subInterests: [
          'Cultural Immersion',
          'Historical Sites & Ruins',
          'Food Tourism',
          'Wildlife Safaris',
          'National Parks',
          'Beach & Island Hopping',
          'City Breaks',
          'Festival Travel',
          'Language Immersion',
          'Voluntourism',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Lifestyle & Wellness',
    icon: LucideIcons.sparkles,
    parents: [
      ParentInterest(
        name: 'Mind & Wellbeing',
        subInterests: [
          'Meditation',
          'Mindfulness',
          'Breathwork',
          'Cold Plunge & Ice Baths',
          'Philosophy',
          'Self-Improvement',
          'Therapy & Inner Work',
          'Sleep Optimisation',
          'Digital Detox',
        ],
      ),
      ParentInterest(
        name: 'Nature & Gardening',
        subInterests: [
          'Houseplants',
          'Bonsai',
          'Vegetable Gardening',
          'Aquascaping',
          'Foraging & Herbalism',
          'Beekeeping',
          'Permaculture',
        ],
      ),
      ParentInterest(
        name: 'Fashion & Style',
        subInterests: [
          'Vintage & Thrifting',
          'Sneaker Culture',
          'Streetwear',
          'Luxury & Designer',
          'Sustainable Fashion',
          'Cottagecore',
          'Gothic & Alternative',
          'Haul Culture',
          'Cosplay',
        ],
      ),
      ParentInterest(
        name: 'Collecting & Hobbies',
        subInterests: [
          'Watch Collecting',
          'Book Collecting',
          'Vinyl Records',
          'Trading Cards',
          'Coins & Currency',
          'Stamps',
          'Art Collecting',
          'Antiques & Vintage',
          'Figurines & Statues',
          'Sports Memorabilia',
        ],
      ),
      ParentInterest(
        name: 'Pets & Animals',
        subInterests: [
          'Dog Training',
          'Cat Care',
          'Exotic Pets',
          'Bird Watching',
          'Aquariums',
          'Animal Rescue & Fostering',
          'Wildlife Photography',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Finance & Business',
    icon: LucideIcons.trendingUp,
    parents: [
      ParentInterest(
        name: 'Investing',
        subInterests: [
          'Stock Market',
          'Index Funds & ETFs',
          'Cryptocurrency',
          'NFTs & Web3',
          'Real Estate Investing',
          'Angel Investing',
          'Options & Derivatives',
          'Commodities',
        ],
      ),
      ParentInterest(
        name: 'Business & Entrepreneurship',
        subInterests: [
          'Startups',
          'Freelancing',
          'E-commerce',
          'Content Creation & Monetisation',
          'Side Hustles',
          'Venture Capital',
          'Marketing & Growth',
          'Product Management',
        ],
      ),
      ParentInterest(
        name: 'Personal Finance',
        subInterests: [
          'FIRE Movement',
          'Frugal Living',
          'Budgeting',
          'Passive Income',
          'Financial Independence',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Social & Activism',
    icon: LucideIcons.users,
    parents: [
      ParentInterest(
        name: 'Community & Volunteering',
        subInterests: [
          'Volunteering',
          'Community Organising',
          'Mutual Aid',
          'Mentorship',
          'Charity & Fundraising',
          'Non-Profit Work',
        ],
      ),
      ParentInterest(
        name: 'Activism & Advocacy',
        subInterests: [
          'Environmental Activism',
          'LGBTQ+ Advocacy',
          'Racial Justice',
          'Gender Equality',
          'Disability Rights',
          'Animal Rights',
          'Anti-War & Peace',
          'Digital Rights',
        ],
      ),
      ParentInterest(
        name: 'Politics & Society',
        subInterests: [
          'Political Science',
          'Current Events',
          'Debate & Discourse',
          'Geopolitics',
          'Local Politics',
          'Journalism & Media Literacy',
        ],
      ),
      ParentInterest(
        name: 'Language & Culture',
        subInterests: [
          'Language Learning',
          'Linguistics',
          'Cultural Exchange',
          'Pen Pals & Letter Writing',
          'Anthropology',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Spirituality & Esoteric',
    icon: LucideIcons.moon,
    parents: [
      ParentInterest(
        name: 'Spiritual Practices',
        subInterests: [
          'Meditation & Prayer',
          'Yoga Philosophy',
          'Buddhism',
          'Hinduism & Vedanta',
          'Sufism',
          'Kabbalah',
          'Shamanism',
          'Druidry & Paganism',
        ],
      ),
      ParentInterest(
        name: 'Mystical & Esoteric',
        subInterests: [
          'Astrology',
          'Tarot & Oracle',
          'Numerology',
          'Crystal Healing',
          'Manifestation',
          'Human Design',
          'Reiki & Energy Healing',
          'Witchcraft',
        ],
      ),
      ParentInterest(
        name: 'Paranormal & Unexplained',
        subInterests: [
          'Ghosts & Hauntings',
          'UFOs & Extraterrestrial',
          'Conspiracy Theories',
          'Cryptids',
          'Near-Death Experiences',
        ],
      ),
    ],
  ),
  InterestCategory(
    name: 'Cars & Motors',
    icon: LucideIcons.car,
    parents: [
      ParentInterest(
        name: 'Cars',
        subInterests: [
          'Car Culture & Shows',
          'Classic & Vintage Cars',
          'JDM (Japanese Domestic Market)',
          'American Muscle',
          'European Sports Cars',
          'Electric Vehicles',
          'Car Modification & Tuning',
          'Off-Road & 4x4',
          'Autocross & Track Days',
          'Formula 1',
          'Rally & Motorsport',
        ],
      ),
      ParentInterest(
        name: 'Motorcycles & Bikes',
        subInterests: [
          'Motorcycles & Touring',
          'Superbikes',
          'Custom & Chopper Builds',
          'Dirt Bikes & Motocross',
          'Cycling (Road)',
          'Mountain Biking',
          'BMX',
          'E-Bikes',
        ],
      ),
      ParentInterest(
        name: 'Aviation & Marine',
        subInterests: [
          'Aviation & Flying',
          'Sailing',
          'Boating & Yachting',
          'Model Aircraft',
        ],
      ),
    ],
  ),
];


abstract final class FilterOptions {
  static const List<String> drinking = [
    'Never',
    'Occasionally',
    'Socially',
    'Regularly',
  ];

  static const List<String> smoking = [
    'Never',
    'Occasionally',
    'Socially',
    'Regularly',
  ];

  static const List<String> childrenPlans = [
    'Want kids',
    "Don't want kids",
    'Undecided',
    'Not specified',
  ];

  static const List<String> religiousBeliefs = [
    // Non-religious / philosophical
    'Atheist',
    'Agnostic',
    'Secular Humanist',
    'Deist',
    'Pantheist',
    // Spiritual but non-denominational
    'Spiritual but not religious',
    'New Age',
    'Pagan / Wiccan',
    // Abrahamic
    'Christian',
    'Catholic',
    'Protestant',
    'Orthodox Christian',
    'Muslim (Sunni)',
    'Muslim (Shia)',
    'Jewish',
    'Jewish (Orthodox)',
    // Dharmic
    'Hindu',
    'Buddhist',
    'Sikh',
    'Jain',
    // East Asian
    'Taoist',
    'Shinto',
    'Confucianist',
    // Other organised religions
    "Bahá'í",
    'Zoroastrian',
    'Rastafari',
    'Druze',
    'Yazidi',
    'Unitarian Universalist',
    // Indigenous / folk
    'Indigenous / Traditional',
    'Animist',
    // Catch-all
    'Other',
    'Prefer not to say',
  ];

  static const List<String> genderOptions = [
    // Binary / cisgender
    'Man',
    'Woman',
    'Cisgender Man',
    'Cisgender Woman',
    // Transgender
    'Transgender Man',
    'Transgender Woman',
    'Transgender',
    // Non-binary umbrella
    'Non-binary',
    'Genderqueer',
    'Genderfluid',
    'Agender',
    'Gender Non-Conforming',
    'Androgynous',
    'Neutrois',
    'Maverique',
    // Multi / split gender
    'Bigender',
    'Trigender',
    'Multigender',
    'Pangender',
    // Demi variants
    'Demiboy',
    'Demigirl',
    'Demi-non-binary',
    // Cultural / other
    'Two-Spirit',
    'Third Gender',
    'Intersex',
    'Xenogender',
    // Open / fluid
    'Queer',
    'Questioning',
    'Prefer not to say',
  ];

  static const List<String> sexualityOptions = [
    // Common orientations
    'Straight / Heterosexual',
    'Gay',
    'Lesbian',
    'Bisexual',
    'Pansexual',
    'Omnisexual',
    'Polysexual',
    // Asexual spectrum
    'Asexual',
    'Graysexual',
    'Demisexual',
    'Cupiosexual',
    'Lithosexual',
    // Aromantic spectrum
    'Aromantic',
    'Aroace',
    'Greyromantic',
    'Demiromantic',
    // Community shorthand
    'Sapphic',
    'Achillean',
    'Queer',
    // Fluid / open
    'Fluid',
    'Skoliosexual',
    'Questioning',
    'Prefer not to say',
  ];

  static const List<String> pronounOptions = [
    // Common
    'he/him',
    'she/her',
    'they/them',
    // Mixed
    'he/they',
    'she/they',
    'he/she',
    'he/she/they',
    // Neopronouns
    'xe/xem',
    'ze/zir',
    'ze/hir',
    'ey/em',
    'fae/faer',
    'per/per',
    'e/em',
    've/ver',
    // Other
    'it/its',
    'any/all',
    'Use my name',
    'Prefer not to say',
  ];

  static const List<String> languages = [
    // Most spoken worldwide
    'English',
    'Mandarin Chinese',
    'Hindi',
    'Spanish',
    'French',
    'Arabic',
    'Bengali',
    'Portuguese',
    'Russian',
    'Urdu',
    'Indonesian / Malay',
    'German',
    'Japanese',
    'Telugu',
    'Marathi',
    'Tamil',
    'Cantonese',
    'Korean',
    'Vietnamese',
    'Turkish',
    'Italian',
    'Punjabi',
    'Gujarati',
    'Persian / Farsi',
    'Polish',
    'Ukrainian',
    'Kannada',
    'Malayalam',
    'Burmese',
    'Thai',
    'Sinhala',
    'Nepali',
    'Tagalog / Filipino',
    'Javanese',
    'Sundanese',
    'Wu Chinese',
    'Swahili',
    'Hausa',
    'Yoruba',
    'Igbo',
    'Amharic',
    'Oromo',
    'Tigrinya',
    'Somali',
    'Zulu',
    'Xhosa',
    'Shona',
    'Kinyarwanda',
    'Lingala',
    'Fula',
    'Wolof',
    'Twi / Akan',
    'Nyanja / Chewa',
    'Sotho',
    'Tswana',
    'Afrikaans',
    // South / Southeast Asia
    'Pashto',
    'Dari',
    'Sindhi',
    'Maithili',
    'Assamese',
    'Khmer',
    'Lao',
    // Central Asia & Caucasus
    'Uzbek',
    'Kazakh',
    'Kyrgyz',
    'Turkmen',
    'Tajik',
    'Azerbaijani',
    'Georgian',
    'Armenian',
    'Kurdish',
    'Mongolian',
    'Tibetan',
    'Uyghur',
    // European
    'Dutch',
    'Greek',
    'Swedish',
    'Norwegian',
    'Danish',
    'Finnish',
    'Hungarian',
    'Romanian',
    'Czech',
    'Slovak',
    'Bulgarian',
    'Serbian',
    'Croatian',
    'Bosnian',
    'Slovenian',
    'Macedonian',
    'Albanian',
    'Lithuanian',
    'Latvian',
    'Estonian',
    'Belarusian',
    'Catalan',
    'Galician',
    'Basque',
    'Welsh',
    'Irish',
    'Scottish Gaelic',
    'Icelandic',
    'Maltese',
    'Luxembourgish',
    // Middle East & North Africa
    'Hebrew',
    // Pacific
    'Malagasy',
    'Fijian',
    'Māori',
    'Hawaiian',
    'Samoan',
    'Tongan',
    // Sign languages
    'American Sign Language (ASL)',
    'British Sign Language (BSL)',
    'International Sign',
    // Constructed / classical
    'Esperanto',
    'Latin',
    'Other',
  ];

  /// Dating tab - maps to `dating_for` TEXT[] column codes.
  static const List<Map<String, String>> datingForOptions = [
    {'code': 'short', 'label': 'Short-term'},
    {'code': 'long', 'label': 'Long-term'},
    {'code': 'casual', 'label': 'Casual Dating'},
    {'code': 'fling', 'label': 'Fling'},
    {'code': 'hookups', 'label': 'Hookups'},
    {'code': 'fwb', 'label': 'Friends w/ Benefits'},
    {'code': 'monogamous', 'label': 'Monogamous'},
    {'code': 'polyamorous', 'label': 'Polyamorous'},
    {'code': 'open_rel', 'label': 'Open Relationship'},
    {'code': 'marriage', 'label': 'Marriage-minded'},
    {'code': 'platonic', 'label': 'Platonic'},
    {'code': 'unsure', 'label': 'Figuring it out'},
  ];

  /// Professional tab - maps to encrypted `looking_for` list field.
  static const List<Map<String, String>> lookingForOptions = [
    {'code': 'networking', 'label': 'Networking'},
    {'code': 'mentorship', 'label': 'Mentorship'},
    {'code': 'cofounder', 'label': 'Co-founder'},
    {'code': 'freelance', 'label': 'Freelance'},
    {'code': 'internship', 'label': 'Internship'},
    {'code': 'long', 'label': 'Long-term role'},
    {'code': 'short', 'label': 'Short-term project'},
  ];

  /// Dating tab - show who filter (maps to candidate search_bucket values).
  static const List<Map<String, String>> searchBuckets = [
    {'code': 'M', 'label': 'Men'},
    {'code': 'F', 'label': 'Women'},
    {'code': 'NB', 'label': 'Non-binary'},
  ];

  static const List<String> partnerValues = [
    'Authenticity',
    'Empathy',
    'Ambition',
    'Loyalty',
    'Honesty',
    'Kindness',
    'Growth Mindset',
    'Creativity',
    'Emotional Maturity',
    'Humor & Wit',
    'Respect',
    'Adventure',
    'Communication',
    'Curiosity',
    'Compassion',
    'Family-oriented',
    'Financial Stability',
    'Independence',
    'Open-mindedness',
    'Self-awareness',
    'Trustworthiness',
  ];

  static const List<String> causesSupported = [
    // Environment & Planet
    'Climate Action',
    'Renewable Energy',
    'Biodiversity & Wildlife',
    'Ocean Conservation',
    'Deforestation & Reforestation',
    'Clean Air',
    'Clean Water & Sanitation',
    'Zero Waste & Recycling',
    'Sustainable Agriculture',
    'Animal Protection',
    'Veganism & Animal Rights',
    // People & Society
    'Human Rights',
    'Gender Equality',
    'LGBTQ+ Rights',
    'Racial Justice',
    'Indigenous Rights',
    'Disability Rights',
    "Children's Rights",
    'Elder Care',
    'Refugee & Migrant Rights',
    'Anti-Trafficking',
    'Prison Reform',
    'Voting Rights & Democracy',
    // Health & Wellbeing
    'Mental Health Advocacy',
    'Global Health',
    'Reproductive Rights',
    'Substance Abuse & Recovery',
    'Nutrition & Food Security',
    'Rare Disease Research',
    // Education & Economy
    'Education Access',
    'Digital Literacy',
    'Economic Development',
    'Poverty Alleviation',
    'Fair Trade',
    'Entrepreneurship & Small Business',
    'Financial Inclusion',
    // Science & Technology
    'Scientific Research',
    'Tech Ethics',
    'AI Safety',
    'Open Source & Open Knowledge',
    'Space Exploration',
    // Culture & Community
    'Arts & Culture Preservation',
    'Community Development',
    'Volunteerism',
    'Religious Freedom',
    'Free Speech & Press Freedom',
    // Humanitarian
    'Disaster Relief',
    'Hunger & Food Banks',
    'Homelessness',
    'Peace & Conflict Resolution',
    'Nuclear Disarmament',
  ];

  static const List<String> pets = [
    // Common companions
    'Dog',
    'Cat',
    'Rabbit',
    'Ferret',
    // Small mammals
    'Hamster',
    'Guinea Pig',
    'Gerbil',
    'Mouse',
    'Rat',
    'Chinchilla',
    'Hedgehog',
    'Sugar Glider',
    'Degu',
    'Prairie Dog',
    // Birds
    'Parrot',
    'Budgie / Parakeet',
    'Cockatiel',
    'Cockatoo',
    'Lovebird',
    'Finch / Canary',
    'Macaw',
    'Pigeon / Dove',
    'Chicken / Poultry',
    // Reptiles
    'Gecko',
    'Bearded Dragon',
    'Tortoise / Turtle',
    'Snake',
    'Iguana',
    'Chameleon',
    'Monitor Lizard',
    // Amphibians
    'Frog / Toad',
    'Axolotl',
    'Salamander',
    // Aquatic
    'Fish (Freshwater)',
    'Fish (Marine / Reef)',
    'Shrimp / Crayfish',
    'Crab',
    // Invertebrates
    'Tarantula',
    'Scorpion',
    'Stick Insect',
    'Snail',
    // Larger / farm-type
    'Horse / Pony',
    'Goat',
    'Sheep',
    'Pig (Micro)',
    'Alpaca / Llama',
    // None
    'No Pets',
  ];

  static const List<String> techSkills = [
    'AI/ML',
    'Web Dev',
    'Mobile Dev',
    'Backend',
    'Cloud/DevOps',
    'Data Science',
    'Cybersecurity',
    'Blockchain',
    'Game Dev',
    'UI/UX',
    'Embedded Systems',
    'Open Source',
  ];

  /// Flat sub-interest values for filtering.
  /// Must match values stored as dict values inside the sub_interests field.
  static const List<String> subInterests = [
    'Photography',
    'Hiking',
    'Gaming',
    'Cooking',
    'Reading',
    'Fitness',
    'Travel',
    'Music',
    'Art',
    'Dance',
    'Theatre',
    'Yoga',
    'Cycling',
    'Swimming',
    'Running',
    'Football',
    'Cricket',
    'Chess',
    'Coding',
    'Startups',
    'Finance',
    'Writing',
    'Podcasting',
    'Films',
    'Anime',
    'Fashion',
    'Sustainability',
    'Volunteering',
  ];
}
