/*
  migration: variant_sync

  purpose:
    - add app_variant column to route profiles into the correct flavor cohort
    - add variant_metadata jsonb for polymorphic onboarding data (major, clubs, etc.)
    - add import/export handshake columns for cross-flavor data transfer
      (flavor → main only; flavor users generate codes, main users consume them)

  notes:
    - all changes are purely additive (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS)
    - the import_sync_code lookup index is partial to skip NULL rows
    - existing profiles default to 'nexus' variant with empty metadata
    - guard_service_fields trigger already blocks client writes to server-owned columns;
      the new sync columns are backend-only and not exposed to client RLS
*/

BEGIN;

-- ==========================================================
-- 1. ADD VARIANT COLUMNS TO profiles
-- ==========================================================

ALTER TABLE public.profiles
    -- Which flavor this profile was created under.
    -- Validated against the known variant list; new variants require a migration.
    ADD COLUMN IF NOT EXISTS app_variant TEXT NOT NULL DEFAULT 'nexus'
        CHECK (app_variant IN ('nexus', 'nexus_mec')),

    -- Tracks whether this profile has already consumed an import handshake.
    -- Prevents re-import once data has been pulled from a flavor account.
    ADD COLUMN IF NOT EXISTS has_imported_data BOOLEAN NOT NULL DEFAULT FALSE,

    -- The one-time 6-character alphanumeric code set by flavor accounts to allow
    -- the main nexus user to pull their data.
    -- NULL means no active export code.
    ADD COLUMN IF NOT EXISTS import_sync_code TEXT UNIQUE,

    -- UTC expiry of the active import_sync_code.
    -- The backend enforces expiry; the database stores the value.
    ADD COLUMN IF NOT EXISTS import_sync_expires_at TIMESTAMP WITH TIME ZONE;


-- ==========================================================
-- 2. INDEXES
-- ==========================================================

-- Partial unique index for O(1) code lookup during import.
-- Skips NULL rows to avoid index bloat from profiles with no active code.
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_import_sync_code
    ON public.profiles (import_sync_code)
    WHERE import_sync_code IS NOT NULL;

-- Partial index for future variant-scoped discovery queries.
CREATE INDEX IF NOT EXISTS idx_profiles_app_variant
    ON public.profiles (app_variant)
    WHERE is_deactivated = FALSE;


-- ==========================================================
-- 2b. RELAX branch / year NOT NULL FOR NEXUS MAIN PROFILES
-- ==========================================================
-- The main 'nexus' flavor does not collect branch or year during onboarding
-- (only name and age are required).
-- MEC profiles must still supply both (enforced at the application layer).
-- PostgreSQL CHECK constraints already pass for NULL values, so no CHECK changes needed.

ALTER TABLE public.profiles
    ALTER COLUMN branch DROP NOT NULL,
    ALTER COLUMN year   DROP NOT NULL;


-- ==========================================================
-- 3. COMMENTS
-- ==========================================================

COMMENT ON COLUMN public.profiles.app_variant
    IS 'Flavor identifier for this profile. Controls which variant-specific UI and onboarding fields apply.';

COMMENT ON COLUMN public.profiles.has_imported_data
    IS 'Set to TRUE after a successful cross-flavor import handshake. Prevents re-import.';

COMMENT ON COLUMN public.profiles.import_sync_code
    IS 'Active 6-character alphanumeric export code generated by a flavor account for one-time data transfer to the main nexus account.';

COMMENT ON COLUMN public.profiles.import_sync_expires_at
    IS 'UTC expiry timestamp for the active import_sync_code. The backend rejects codes past this time.';

COMMIT;
