GENDER_CHOICES = {
    "Man",
    "Woman",
    "Non-binary",
    "Genderqueer",
    "Genderfluid",
    "Agender",
    "Transgender Man",
    "Transgender Woman",
    "Gender Non-Conforming",
    "Pangender",
    "Androgynous",
    "Neutrois",
    "Third Gender",
    "Intersex",
    "Bigender",
    "Two-Spirit",
    "Demiboy",
    "Demigirl",
    "Queer",
    "Questioning",
    "Prefer not to say",
}

SEXUALITY_CHOICES = {
    "Straight",
    "Gay",
    "Lesbian",
    "Bisexual",
    "Pansexual",
    "Asexual",
    "Aromantic",
    "Greysexual",
    "Polysexual",
    "Omnisexual",
    "Fluid",
    "Skoliosexual",
    "Demisexual",
    "Queer",
    "Questioning",
    "Prefer not to say",
}

PRONOUNS_CHOICES = {
    "he/him",
    "she/her",
    "they/them",
    "he/they",
    "she/they",
    "it/its",
    "any/all",
    "xe/xem",
    "fae/faer",
    "Prefer not to say",
}

LANGUAGES_CHOICES = {
    "English",
    "Spanish",
    "Mandarin Chinese",
    "Hindi",
    "Arabic",
    "Portuguese",
    "Bengali",
    "Russian",
    "Japanese",
    "Punjabi",
    "German",
    "Javanese",
    "Wu Chinese",
    "Malay",
    "Telugu",
    "Vietnamese",
    "Korean",
    "French",
    "Marathi",
    "Tamil",
    "Cantonese",
    "Turkish",
    "Urdu",
    "Italian",
    "Thai",
    "Persian",
    "Polish",
    "Kannada",
    "Ukrainian",
    "Filipino",
    "Gujarati",
    "Romanian",
    "Greek",
    "Czech",
    "Swedish",
    "Dutch",
    "Hungarian",
    "Zulu",
    "Hebrew",
    "Finnish",
    "Norwegian",
    "Danish",
    "Swahili",
    "Malayalam",
    "Amharic",
    "Yoruba",
    "Oromo",
    "Igbo",
    "Burmese",
    "Azerbaijani",
    "Maithili",
    "Uzbek",
    "Sindhi",
    "Pashto",
    "Kurdish",
    "Sinhala",
    "Somali",
    "Tagalog",
    "Nepali",
    "Khmer",
    "Lao",
    "Assamese",
    "Malagasy",
    "Slovak",
    "Bulgarian",
    "Croatian",
    "Serbian",
    "Lithuanian",
    "Latvian",
    "Estonian",
    "Slovenian",
    "Irish",
    "Welsh",
    "Icelandic",
    "Catalan",
    "Basque",
    "Galician",
    "Textile",
}

CAUSES_SUPPORTED_CHOICES = {
    "Climate Action",
    "Tech Ethics",
    "Mental Health",
    "LGBTQ+ Rights",
    "Education Access",
    "Animal Protection",
    "Disaster Relief",
    "Poverty Alleviation",
    "Gender Equality",
    "Scientific Research",
    "Mental Health Advocacy",
    "Human Rights",
    "Clean Water & Sanitation",
    "Renewable Energy",
    "Economic Development",
    "Arts & Culture Preservation",
}

PETS_CHOICES = {
    "Dog",
    "Cat",
    "Fish",
    "Bird",
    "Rabbit",
    "Hamster",
    "Guinea Pig",
    "Ferret",
    "Reptile",
    "Amphibian",
    "Horse",
    "Chicken",
    "Sugar Glider",
    "Chinchilla",
    "Hedgehog",
    "No Pets",
}

DRINKING_CHOICES = {"Never", "Occasionally", "Socially", "Regularly"}

SMOKING_CHOICES = {"Never", "Occasionally", "Socially", "Regularly"}

CHILDREN_PLANS_CHOICES = {
    "Want kids",
    "Don't want kids",
    "Undecided",
    "Not specified",
}

RELIGIOUS_BELIEFS_CHOICES = {
    "Atheist",
    "Agnostic",
    "Spiritual",
    "Christian",
    "Muslim",
    "Jewish",
    "Hindu",
    "Buddhist",
    "Sikh",
    "Jain",
    "Other",
    "Not specified",
}

VALID_INTERESTS = {
    'Coding': {
        'Python',
        'Flutter & Dart',
        'Rust',
        'Web Development',
        'AI & Machine Learning',
        'Cybersecurity',
        'Game Development',
        'Cloud & DevOps',
        'Open Source Contribution',
        'Mobile Apps',
    },
    'Science & Discovery': {
        'Astrophysics & Space',
        'Quantum Physics',
        'Neuroscience',
        'Psychology',
        'Marine Biology',
        'Archaeology & History',
        'Genetics & Biotech',
        'Climate Science',
    },
    'Gadgets & Hardware': {
        'PC Building',
        'Virtual Reality (VR)',
        'Drones & Quadcopters',
        'IoT & Smart Home',
        'Mechanical Keyboards',
        '3D Printing',
        'Robotics',
    },
    'Math & Logic': {
        'Cryptography',
        'Data Analysis',
        'Game Theory',
        'Mathematical Puzzles',
        'Algorithms',
    },
    'Watching TV & Series': {
        'Horror Shows',
        'Sci-Fi & Fantasy',
        'Documentaries',
        'True Crime',
        'Sitcoms & Comedy',
        'K-Dramas',
        'Anime & Manga',
        'Reality TV',
        'Historical Drama',
        'Talk Shows',
    },
    'Movies & Cinema': {
        'Indie & Art House',
        'Hollywood Blockbusters',
        'Classic Films',
        'Psychological Thrillers',
        'Animation & Pixar',
        'Foreign Language Films',
        'Action & Adventure',
    },
    'Gaming': {
        'RPGs (Role-Playing)',
        'FPS (First-Person)',
        'RTS (Strategy)',
        'MMORPGs',
        'Cozy & Casual Games',
        'Competitive Esports',
        'Retro & Arcade',
        'Tabletop & D&D',
        'Modern Board Games',
    },
    'Music & Sound': {
        'Rock & Metal',
        'Pop & R&B',
        'Hip Hop & Rap',
        'Indie & Folk',
        'Classical & Jazz',
        'EDM & Synthwave',
        'Lo-Fi & Chillbeats',
        'Podcasts & Audiobooks',
        'Vinyl Records',
    },
    'Fitness & Training': {
        'Weightlifting',
        'Powerlifting',
        'CrossFit',
        'Calisthenics',
        'Yoga & Pilates',
        'HIIT & Cardio',
        'Spinning & Cycling',
        'Gymnastics',
    },
    'Team Sports': {
        'Football (Soccer)',
        'Basketball',
        'Volleyball',
        'Baseball',
        'Cricket',
        'American Football',
        'Rugby',
        'Ice Hockey',
    },
    'Individual Sports': {
        'Tennis',
        'Badminton',
        'Table Tennis',
        'Golf',
        'Archery',
        'Fencing',
        'Billiards & Pool',
    },
    'Water & Winter Sports': {
        'Swimming & Diving',
        'Surfing & Bodyboarding',
        'Kayaking & Paddle',
        'Scuba Diving',
        'Skiing',
        'Snowboarding',
        'Ice Skating',
    },
    'Outdoor Adventure': {
        'Hiking & Trekking',
        'Rock Climbing',
        'Camping & Bushcraft',
        'Backpacking',
        'Mountaineering',
        'Trail Running',
        'Geocaching',
    },
    'Visual Arts': {
        'Watercolor Painting',
        'Oil & Acrylics',
        'Sketching & Charcoal',
        'Digital Illustration',
        'Calligraphy',
        'Pottery & Ceramics',
        'Origami & Papercraft',
    },
    'Design & Styling': {
        'UI/UX Design',
        'Graphic Design',
        'Fashion & Apparel',
        'Interior Design',
        '3D Modeling',
        'Architecture',
    },
    'Photography & Video': {
        'Landscape & Nature',
        'Portrait & Studio',
        'Street & Documentary',
        'Film & Analog',
        'Drone Videography',
        'Video Editing',
    },
    'Performing Arts': {
        'Dancing',
        'Acting & Theater',
        'Musical Instruments',
        'Singing & Vocals',
        'Stand-up & Improv',
    },
    'Writing & Literature': {
        'Creative Writing',
        'Poetry & Prose',
        'Blogging & Journalism',
        'Journaling',
    },
    'Cooking & Culinary': {
        'Baking & Pastry',
        'Sourdough Bread',
        'BBQ & Grilling',
        'Vegan & Vegetarian',
        'Fine Dining',
        'Fermentation',
        'Meal Prep & Nutrition',
    },
    'Beverages': {
        'Specialty Coffee',
        'Matcha & Green Tea',
        'Loose Leaf Tea',
        'Wine Tasting',
        'Craft Beer Brewing',
        'Mixology & Cocktails',
    },
    'Nature & Gardening': {
        'Houseplants',
        'Bonsai Trees',
        'Vegetable Gardening',
        'Aquascaping',
        'Foraging & Herbalism',
    },
    'Mind & Wellness': {
        'Meditation',
        'Philosophy',
        'Astrology & Tarot',
        'Self-Improvement',
        'Volunteering',
    },
    'Fashion & Collecting': {
        'Vintage & Thrifting',
        'Sneaker Culture',
        'Streetwear',
        'Watch Collecting',
        'Book Collecting',
    },
    'Pets & Animals': {
        'Dogs & Dog Training',
        'Cats & Felines',
        'Reptiles',
        'Aquariums & Fish',
        'Bird Watching',
    },
}

