"""Predefined validation choice sets and taxonomy mappings.

Contains canonical sets for user profile options including gender identities, sexualities,
pronouns, spoken languages, supported causes, pets, lifestyle habits, and structured interest taxonomies.
"""

GENDER_CHOICES = {

    # Binary / cisgender
    "Man",
    "Woman",
    "Cisgender Man",
    "Cisgender Woman",
    # Transgender
    "Transgender Man",
    "Transgender Woman",
    "Transgender",
    # Non-binary umbrella
    "Non-binary",
    "Genderqueer",
    "Genderfluid",
    "Agender",
    "Gender Non-Conforming",
    "Androgynous",
    "Neutrois",
    "Maverique",
    # Multi / split gender
    "Bigender",
    "Trigender",
    "Multigender",
    "Pangender",
    # Demi variants
    "Demiboy",
    "Demigirl",
    "Demi-non-binary",
    # Cultural / other
    "Two-Spirit",
    "Third Gender",
    "Intersex",
    "Xenogender",
    # Open / fluid
    "Queer",
    "Questioning",
    "Prefer not to say",
}

SEXUALITY_CHOICES = {
    # Common orientations
    "Straight / Heterosexual",
    "Gay",
    "Lesbian",
    "Bisexual",
    "Pansexual",
    "Omnisexual",
    "Polysexual",
    # Asexual spectrum
    "Asexual",
    "Graysexual",
    "Demisexual",
    "Cupiosexual",
    "Lithosexual",
    # Aromantic spectrum
    "Aromantic",
    "Aroace",
    "Greyromantic",
    "Demiromantic",
    # Community shorthand
    "Sapphic",
    "Achillean",
    "Queer",
    # Fluid / open
    "Fluid",
    "Skoliosexual",
    "Questioning",
    "Prefer not to say",
}

PRONOUNS_CHOICES = {
    # Common
    "he/him",
    "she/her",
    "they/them",
    # Mixed
    "he/they",
    "she/they",
    "he/she",
    "he/she/they",
    # Neopronouns
    "xe/xem",
    "ze/zir",
    "ze/hir",
    "ey/em",
    "fae/faer",
    "per/per",
    "e/em",
    "ve/ver",
    # Other
    "it/its",
    "any/all",
    "Use my name",
    "Prefer not to say",
}

LANGUAGES_CHOICES = {
    # Most spoken worldwide
    "English",
    "Mandarin Chinese",
    "Hindi",
    "Spanish",
    "French",
    "Arabic",
    "Bengali",
    "Portuguese",
    "Russian",
    "Urdu",
    "Indonesian / Malay",
    "German",
    "Japanese",
    "Telugu",
    "Marathi",
    "Tamil",
    "Cantonese",
    "Korean",
    "Vietnamese",
    "Turkish",
    "Italian",
    "Punjabi",
    "Gujarati",
    "Persian / Farsi",
    "Polish",
    "Ukrainian",
    "Kannada",
    "Malayalam",
    "Burmese",
    "Thai",
    "Sinhala",
    "Nepali",
    "Tagalog / Filipino",
    "Javanese",
    "Sundanese",
    "Wu Chinese",
    "Swahili",
    "Hausa",
    "Yoruba",
    "Igbo",
    "Amharic",
    "Oromo",
    "Tigrinya",
    "Somali",
    "Zulu",
    "Xhosa",
    "Shona",
    "Kinyarwanda",
    "Lingala",
    "Fula",
    "Wolof",
    "Twi / Akan",
    "Nyanja / Chewa",
    "Sotho",
    "Tswana",
    "Afrikaans",
    # South / Southeast Asia
    "Pashto",
    "Dari",
    "Sindhi",
    "Maithili",
    "Assamese",
    "Khmer",
    "Lao",
    # Central Asia & Caucasus
    "Uzbek",
    "Kazakh",
    "Kyrgyz",
    "Turkmen",
    "Tajik",
    "Azerbaijani",
    "Georgian",
    "Armenian",
    "Kurdish",
    "Mongolian",
    "Tibetan",
    "Uyghur",
    # European
    "Dutch",
    "Greek",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "Hungarian",
    "Romanian",
    "Czech",
    "Slovak",
    "Bulgarian",
    "Serbian",
    "Croatian",
    "Bosnian",
    "Slovenian",
    "Macedonian",
    "Albanian",
    "Lithuanian",
    "Latvian",
    "Estonian",
    "Belarusian",
    "Catalan",
    "Galician",
    "Basque",
    "Welsh",
    "Irish",
    "Scottish Gaelic",
    "Icelandic",
    "Maltese",
    "Luxembourgish",
    # Middle East & North Africa
    "Hebrew",
    # Pacific
    "Malagasy",
    "Fijian",
    "Māori",
    "Hawaiian",
    "Samoan",
    "Tongan",
    # Sign languages
    "American Sign Language (ASL)",
    "British Sign Language (BSL)",
    "International Sign",
    # Constructed / classical
    "Esperanto",
    "Latin",
    "Other",
}

CAUSES_SUPPORTED_CHOICES = {
    # Environment & Planet
    "Climate Action",
    "Renewable Energy",
    "Biodiversity & Wildlife",
    "Ocean Conservation",
    "Deforestation & Reforestation",
    "Clean Air",
    "Clean Water & Sanitation",
    "Zero Waste & Recycling",
    "Sustainable Agriculture",
    "Animal Protection",
    "Veganism & Animal Rights",
    # People & Society
    "Human Rights",
    "Gender Equality",
    "LGBTQ+ Rights",
    "Racial Justice",
    "Indigenous Rights",
    "Disability Rights",
    "Children's Rights",
    "Elder Care",
    "Refugee & Migrant Rights",
    "Anti-Trafficking",
    "Prison Reform",
    "Voting Rights & Democracy",
    # Health & Wellbeing
    "Mental Health Advocacy",
    "Global Health",
    "Reproductive Rights",
    "Substance Abuse & Recovery",
    "Nutrition & Food Security",
    "Rare Disease Research",
    # Education & Economy
    "Education Access",
    "Digital Literacy",
    "Economic Development",
    "Poverty Alleviation",
    "Fair Trade",
    "Entrepreneurship & Small Business",
    "Financial Inclusion",
    # Science & Technology
    "Scientific Research",
    "Tech Ethics",
    "AI Safety",
    "Open Source & Open Knowledge",
    "Space Exploration",
    # Culture & Community
    "Arts & Culture Preservation",
    "Community Development",
    "Volunteerism",
    "Religious Freedom",
    "Free Speech & Press Freedom",
    # Humanitarian
    "Disaster Relief",
    "Hunger & Food Banks",
    "Homelessness",
    "Peace & Conflict Resolution",
    "Nuclear Disarmament",
}

PETS_CHOICES = {
    # Common companions
    "Dog",
    "Cat",
    "Rabbit",
    "Ferret",
    # Small mammals
    "Hamster",
    "Guinea Pig",
    "Gerbil",
    "Mouse",
    "Rat",
    "Chinchilla",
    "Hedgehog",
    "Sugar Glider",
    "Degu",
    "Prairie Dog",
    # Birds
    "Parrot",
    "Budgie / Parakeet",
    "Cockatiel",
    "Cockatoo",
    "Lovebird",
    "Finch / Canary",
    "Macaw",
    "Pigeon / Dove",
    "Chicken / Poultry",
    # Reptiles
    "Gecko",
    "Bearded Dragon",
    "Tortoise / Turtle",
    "Snake",
    "Iguana",
    "Chameleon",
    "Monitor Lizard",
    # Amphibians
    "Frog / Toad",
    "Axolotl",
    "Salamander",
    # Aquatic
    "Fish (Freshwater)",
    "Fish (Marine / Reef)",
    "Shrimp / Crayfish",
    "Crab",
    # Invertebrates
    "Tarantula",
    "Scorpion",
    "Stick Insect",
    "Snail",
    # Larger / farm-type
    "Horse / Pony",
    "Goat",
    "Sheep",
    "Pig (Micro)",
    "Alpaca / Llama",
    # None
    "No Pets",
}

DRINKING_CHOICES = {"Never", "Occasionally", "Socially", "Regularly"}

SMOKING_CHOICES = {"Never", "Occasionally", "Socially", "Regularly"}

CHILDREN_PLANS_CHOICES = {
    "Want kids",
    "Don't want kids",
    "Undecided",
    "Not specified",
}

RELIGIOUS_BELIEFS_CHOICES = {
    # Non-religious / philosophical
    "Atheist",
    "Agnostic",
    "Secular Humanist",
    "Deist",
    "Pantheist",
    # Spiritual but non-denominational
    "Spiritual but not religious",
    "New Age",
    "Pagan / Wiccan",
    # Abrahamic
    "Christian",
    "Catholic",
    "Protestant",
    "Orthodox Christian",
    "Muslim (Sunni)",
    "Muslim (Shia)",
    "Jewish",
    "Jewish (Orthodox)",
    # Dharmic
    "Hindu",
    "Buddhist",
    "Sikh",
    "Jain",
    # East Asian
    "Taoist",
    "Shinto",
    "Confucianist",
    # Other organised religions
    "Bahá'í",
    "Zoroastrian",
    "Rastafari",
    "Druze",
    "Yazidi",
    "Unitarian Universalist",
    # Indigenous / folk
    "Indigenous / Traditional",
    "Animist",
    # Catch-all
    "Other",
    "Prefer not to say",
}

VALID_INTERESTS = {
    # --- Tech & Science ---
    "Coding": {
        "Python",
        "Flutter & Dart",
        "Rust",
        "JavaScript & TypeScript",
        "Web Development",
        "AI & Machine Learning",
        "Cybersecurity",
        "Game Development",
        "Cloud & DevOps",
        "Open Source Contribution",
        "Mobile Apps",
        "Embedded Systems",
        "Blockchain & Web3",
    },
    "Science & Discovery": {
        "Astrophysics & Space",
        "Quantum Physics",
        "Neuroscience",
        "Psychology",
        "Marine Biology",
        "Archaeology & History",
        "Genetics & Biotech",
        "Climate Science",
        "Chemistry",
        "Mathematics",
        "Citizen Science",
    },
    "Gadgets & Hardware": {
        "PC Building",
        "Virtual Reality (VR)",
        "Augmented Reality (AR)",
        "Drones & Quadcopters",
        "IoT & Smart Home",
        "Mechanical Keyboards",
        "3D Printing",
        "Robotics",
        "Amateur Radio (Ham)",
    },
    "Math & Logic": {
        "Cryptography",
        "Data Analysis",
        "Game Theory",
        "Mathematical Puzzles",
        "Algorithms",
        "Chess & Strategy Games",
    },
    # --- Entertainment & Media ---
    "TV & Series": {
        "Horror Shows",
        "Sci-Fi & Fantasy",
        "Documentaries",
        "True Crime",
        "Sitcoms & Comedy",
        "K-Dramas",
        "Anime & Manga",
        "Reality TV",
        "Historical Drama",
        "Talk Shows",
        "Mini-Series & Limited",
        "Soap Operas",
        "Telenovelas",
    },
    "Movies & Cinema": {
        "Indie & Art House",
        "Hollywood Blockbusters",
        "Classic Films",
        "Psychological Thrillers",
        "Animation & Pixar",
        "Foreign Language Films",
        "Action & Adventure",
        "Horror",
        "Rom-Coms",
        "Bollywood",
        "Martial Arts Films",
        "Documentaries",
    },
    "Gaming": {
        "RPGs (Role-Playing)",
        "FPS (First-Person)",
        "RTS (Strategy)",
        "MMORPGs",
        "Cozy & Casual Games",
        "Competitive Esports",
        "Retro & Arcade",
        "Tabletop & D&D",
        "Modern Board Games",
        "Card Games (TCG)",
        "Puzzle Games",
        "Horror Games",
        "Simulation & Sandbox",
        "Sports Games",
        "Fighting Games",
        "Mobile Gaming",
    },
    "Music": {
        "Rock & Alternative",
        "Metal & Heavy",
        "Pop",
        "R&B & Soul",
        "Hip Hop & Rap",
        "Indie & Folk",
        "Classical & Opera",
        "Jazz & Blues",
        "EDM & House",
        "Techno & Industrial",
        "Synthwave & Retrowave",
        "Lo-Fi & Chillbeats",
        "Reggae & Dancehall",
        "Afrobeats & Afropop",
        "Latin & Reggaeton",
        "K-Pop",
        "Country & Bluegrass",
        "Gospel & Worship",
        "Punk & Hardcore",
        "Ambient & Drone",
        "Vinyl Records",
        "Live Concerts & Festivals",
        "Music Production",
    },
    "Comedy & Memes": {
        "Meme Culture",
        "Stand-Up Comedy",
        "Sketch Comedy",
        "Improv",
        "Internet Humour",
        "Satire",
        "Podcasts (Comedy)",
    },
    "Podcasts & Audio": {
        "True Crime Podcasts",
        "News & Current Affairs",
        "Self-Improvement Podcasts",
        "Science Podcasts",
        "Storytelling & Fiction",
        "Interview Shows",
        "Audiobooks",
    },
    # --- Sports & Outdoors ---
    "Fitness & Training": {
        "Weightlifting",
        "Powerlifting",
        "CrossFit",
        "Calisthenics",
        "Yoga",
        "Pilates",
        "HIIT & Cardio",
        "Cycling & Spinning",
        "Gymnastics",
        "Running & Marathons",
        "Triathlons",
        "Personal Training",
        "Dance Fitness",
    },
    "Martial Arts & Combat": {
        "Boxing",
        "Muay Thai",
        "Brazilian Jiu-Jitsu (BJJ)",
        "Wrestling",
        "MMA",
        "Karate",
        "Judo",
        "Taekwondo",
        "Kickboxing",
        "Krav Maga",
        "Capoeira",
        "Kung Fu",
    },
    "Team Sports": {
        "Football (Soccer)",
        "Basketball",
        "Volleyball",
        "Baseball",
        "Cricket",
        "American Football",
        "Rugby",
        "Ice Hockey",
        "Lacrosse",
        "Water Polo",
        "Handball",
        "Ultimate Frisbee",
        "Netball",
    },
    "Individual Sports": {
        "Tennis",
        "Badminton",
        "Table Tennis",
        "Golf",
        "Archery",
        "Fencing",
        "Billiards & Pool",
        "Track & Field",
        "Cycling (Road)",
        "Cycling (MTB)",
        "Skateboarding",
        "Parkour",
        "Equestrian",
    },
    "Water & Winter Sports": {
        "Swimming",
        "Open Water Swimming",
        "Surfing & Bodyboarding",
        "Kayaking & Paddle",
        "Scuba Diving",
        "Snorkelling",
        "Sailing",
        "Kitesurfing",
        "Skiing",
        "Snowboarding",
        "Ice Skating",
        "Freediving",
    },
    "Outdoor Adventure": {
        "Hiking & Trekking",
        "Rock Climbing",
        "Bouldering",
        "Camping & Bushcraft",
        "Backpacking",
        "Mountaineering",
        "Trail Running",
        "Geocaching",
        "Foraging",
        "Caving & Spelunking",
        "Paragliding",
        "Skydiving",
        "Hunting & Fishing",
    },
    "Watching Sports": {
        "Football Watching",
        "Basketball Watching",
        "Formula 1",
        "MMA & UFC",
        "Cricket Watching",
        "Tennis Watching",
        "Olympic Sports",
        "Fantasy Leagues",
    },
    # --- Creative & Arts ---
    "Visual Arts": {
        "Watercolor Painting",
        "Oil & Acrylics",
        "Sketching & Charcoal",
        "Digital Illustration",
        "Calligraphy",
        "Pottery & Ceramics",
        "Origami & Papercraft",
        "Printmaking",
        "Sculpture",
        "Street Art & Graffiti",
        "Collage & Mixed Media",
    },
    "Design & Styling": {
        "UI/UX Design",
        "Graphic Design",
        "Fashion Design",
        "Interior Design",
        "3D Modeling",
        "Architecture",
        "Typesetting",
        "Logo Design",
        "Jewellery Making",
    },
    "Photography & Video": {
        "Landscape & Nature",
        "Portrait & Studio",
        "Street & Documentary",
        "Film & Analog",
        "Drone Videography",
        "Video Editing",
        "YouTube & Content Creation",
        "Wedding & Events",
    },
    "Performing Arts": {
        "Ballet",
        "Contemporary Dance",
        "Hip Hop Dance",
        "Ballroom & Latin Dance",
        "Salsa & Bachata",
        "Traditional Dance",
        "Acting & Theater",
        "Musical Theater",
        "Musical Instruments",
        "Singing & Vocals",
        "Choir",
        "Stand-Up & Improv",
        "Circus Arts",
        "Magic & Illusion",
    },
    "Writing & Literature": {
        "Creative Fiction",
        "Fantasy & Sci-Fi Writing",
        "Poetry & Prose",
        "Blogging & Journalism",
        "Journaling",
        "Screenwriting",
        "Game Writing",
        "Technical Writing",
    },
    "Crafts & DIY": {
        "Knitting & Crocheting",
        "Sewing & Embroidery",
        "Woodworking & Carpentry",
        "Leatherworking",
        "Candle & Soap Making",
        "Model Building",
        "RC Vehicles",
        "Lego & Sets",
        "Macramé",
        "Resin Art",
        "Home Renovation & DIY",
    },
    # --- Books & Reading ---
    "Fiction": {
        "Fantasy",
        "Science Fiction",
        "Literary Fiction",
        "Historical Fiction",
        "Romance",
        "Thriller & Mystery",
        "Horror",
        "Magical Realism",
        "Graphic Novels & Comics",
        "Manga",
    },
    "Non-Fiction": {
        "Biographies & Memoirs",
        "Self-Help",
        "Philosophy",
        "History",
        "Science & Nature",
        "Psychology",
        "Business & Economics",
        "True Crime Books",
        "Political Theory",
        "Travel Writing",
        "Essays & Criticism",
        "Spirituality & Religion",
    },
    "Reading Habits": {
        "Book Clubs",
        "Audiobooks",
        "eBooks",
        "Second-Hand Books",
        "Reading Challenges",
        "Rare & Antique Books",
    },
    # --- Food & Drink ---
    "Cooking & Culinary": {
        "Baking & Pastry",
        "Sourdough Bread",
        "BBQ & Grilling",
        "Vegan & Vegetarian Cooking",
        "World Cuisines",
        "Fine Dining",
        "Fermentation & Pickling",
        "Meal Prep & Nutrition",
        "Street Food",
        "Sushi & Japanese Cuisine",
        "Middle Eastern Cuisine",
        "Italian Cooking",
        "Indian Cooking",
    },
    "Beverages": {
        "Specialty Coffee",
        "Matcha & Green Tea",
        "Loose Leaf Tea",
        "Wine Tasting",
        "Craft Beer & Brewing",
        "Mixology & Cocktails",
        "Natural Wine",
        "Kombucha & Fermented Drinks",
        "Whisky & Spirits",
        "Non-Alcoholic Cocktails",
    },
    "Food Culture": {
        "Restaurant Hopping",
        "Food Photography",
        "Food Blogging",
        "Farmers Markets",
        "Food Festivals",
    },
    # --- Travel & Adventure ---
    "Travel Style": {
        "Backpacking",
        "Solo Travel",
        "Luxury Travel",
        "Budget Travel",
        "Van Life & Overlanding",
        "Road Trips",
        "Cruise Travel",
        "Family Travel",
        "Workcation & Remote Work",
        "Digital Nomad Lifestyle",
    },
    "Destinations": {
        "Europe",
        "Southeast Asia",
        "East Asia",
        "South Asia",
        "Africa",
        "Latin America",
        "Middle East",
        "North America",
        "Oceania & Pacific",
        "Arctic & Antarctic",
    },
    "Travel Interests": {
        "Cultural Immersion",
        "Historical Sites & Ruins",
        "Food Tourism",
        "Wildlife Safaris",
        "National Parks",
        "Beach & Island Hopping",
        "City Breaks",
        "Festival Travel",
        "Language Immersion",
        "Voluntourism",
    },
    # --- Lifestyle & Wellness ---
    "Mind & Wellbeing": {
        "Meditation",
        "Mindfulness",
        "Breathwork",
        "Cold Plunge & Ice Baths",
        "Philosophy",
        "Self-Improvement",
        "Therapy & Inner Work",
        "Sleep Optimisation",
        "Digital Detox",
    },
    "Nature & Gardening": {
        "Houseplants",
        "Bonsai",
        "Vegetable Gardening",
        "Aquascaping",
        "Foraging & Herbalism",
        "Beekeeping",
        "Permaculture",
    },
    "Fashion & Style": {
        "Vintage & Thrifting",
        "Sneaker Culture",
        "Streetwear",
        "Luxury & Designer",
        "Sustainable Fashion",
        "Cottagecore",
        "Gothic & Alternative",
        "Haul Culture",
        "Cosplay",
    },
    "Collecting & Hobbies": {
        "Watch Collecting",
        "Book Collecting",
        "Vinyl Records",
        "Trading Cards",
        "Coins & Currency",
        "Stamps",
        "Art Collecting",
        "Antiques & Vintage",
        "Figurines & Statues",
        "Sports Memorabilia",
    },
    "Pets & Animals": {
        "Dog Training",
        "Cat Care",
        "Exotic Pets",
        "Bird Watching",
        "Aquariums",
        "Animal Rescue & Fostering",
        "Wildlife Photography",
    },
    # --- Finance & Business ---
    "Investing": {
        "Stock Market",
        "Index Funds & ETFs",
        "Cryptocurrency",
        "NFTs & Web3",
        "Real Estate Investing",
        "Angel Investing",
        "Options & Derivatives",
        "Commodities",
    },
    "Business & Entrepreneurship": {
        "Startups",
        "Freelancing",
        "E-commerce",
        "Content Creation & Monetisation",
        "Side Hustles",
        "Venture Capital",
        "Marketing & Growth",
        "Product Management",
    },
    "Personal Finance": {
        "FIRE Movement",
        "Frugal Living",
        "Budgeting",
        "Passive Income",
        "Financial Independence",
    },
    # --- Social & Activism ---
    "Community & Volunteering": {
        "Volunteering",
        "Community Organising",
        "Mutual Aid",
        "Mentorship",
        "Charity & Fundraising",
        "Non-Profit Work",
    },
    "Activism & Advocacy": {
        "Environmental Activism",
        "LGBTQ+ Advocacy",
        "Racial Justice",
        "Gender Equality",
        "Disability Rights",
        "Animal Rights",
        "Anti-War & Peace",
        "Digital Rights",
    },
    "Politics & Society": {
        "Political Science",
        "Current Events",
        "Debate & Discourse",
        "Geopolitics",
        "Local Politics",
        "Journalism & Media Literacy",
    },
    "Language & Culture": {
        "Language Learning",
        "Linguistics",
        "Cultural Exchange",
        "Pen Pals & Letter Writing",
        "Anthropology",
    },
    # --- Spirituality & Esoteric ---
    "Spiritual Practices": {
        "Meditation & Prayer",
        "Yoga Philosophy",
        "Buddhism",
        "Hinduism & Vedanta",
        "Sufism",
        "Kabbalah",
        "Shamanism",
        "Druidry & Paganism",
    },
    "Mystical & Esoteric": {
        "Astrology",
        "Tarot & Oracle",
        "Numerology",
        "Crystal Healing",
        "Manifestation",
        "Human Design",
        "Reiki & Energy Healing",
        "Witchcraft",
    },
    "Paranormal & Unexplained": {
        "Ghosts & Hauntings",
        "UFOs & Extraterrestrial",
        "Conspiracy Theories",
        "Cryptids",
        "Near-Death Experiences",
    },
    # --- Cars & Motors ---
    "Cars": {
        "Car Culture & Shows",
        "Classic & Vintage Cars",
        "JDM (Japanese Domestic Market)",
        "American Muscle",
        "European Sports Cars",
        "Electric Vehicles",
        "Car Modification & Tuning",
        "Off-Road & 4x4",
        "Autocross & Track Days",
        "Formula 1",
        "Rally & Motorsport",
    },
    "Motorcycles & Bikes": {
        "Motorcycles & Touring",
        "Superbikes",
        "Custom & Chopper Builds",
        "Dirt Bikes & Motocross",
        "Cycling (Road)",
        "Mountain Biking",
        "BMX",
        "E-Bikes",
    },
    "Aviation & Marine": {
        "Aviation & Flying",
        "Sailing",
        "Boating & Yachting",
        "Model Aircraft",
    },
}
